import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import Navbar from '@/components/NavBar';
import logo_horizontal from '@/public/logo_horiziotal.png';
import Image from 'next/image';

const inter = Inter({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body className={inter.className}>
        <div className={'bg-black'}>
          <Image
            className={'w-full bg-black p-5  md:hidden '}
            src={logo_horizontal}
            alt={'logo'}
          />
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
